language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
  directories:
    - $HOME/.ccache
dist: xenial
osx_image: xcode11
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - ccache
      - pkg-config
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - ninja-build
  homebrew:
    packages:
      - ccache
      - ninja
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - "sudo chown -R travis: $HOME/.ccache"
  - export PATH="/usr/local/opt/ccache/libexec:/usr/lib/ccache:$PATH"
  - if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then rustup component add clippy-preview || true; fi
  - cargo install cargo-kcov || echo "cargo-kcov already installed"
  - mkdir kcov
  - wget -O - https://github.com/SimonKagstrom/kcov/archive/v36.tar.gz | tar xz -C kcov --strip-components 1
  - mkdir -p kcov/build && cd kcov/build
  - cmake .. -G"Ninja" -DCMAKE_BUILD_TYPE=Release
  - sudo ninja install
script:
  - if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then cargo clippy || true; fi
  - cargo build --verbose --all
  - cargo clean
  - RUSTFLAGS="-C link-dead-code" cargo test --no-run
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then travis_wait cargo kcov -v --coveralls --no-clean-rebuild; fi
