language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
dist: xenial
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo build --verbose --all
  - cargo test --verbose --all || true