[package]
name = "example-project"
version = "0.1.0"
edition = "2021"

[features]
capi = ["libc"]

[dependencies]
libc = { version = "0.2", optional = true }

[package.metadata.capi.header]
subdirectory = false
